### ISSUE TITLE
This app is hanging while making call to Twitch

### ISSUE THREAD

**Issue by LizzieA69** [buzz/twitch-indicator#18]
I use Manjaro-ARM XFCE in a Raspberry Pi 400. When I run the app is sends the call to Twitch but then stops and shows in dark gray Checking... and Live channels and doesn't change to show the live channels. This happened after I cleared out profile pics from the app's folder located in .cache. I know Twitch is currently up and running at the time of this post. Also, I have a browser extinction that does the same thing as your app, and it shows me the live channels, so I know Twitch hasn't blocked that functionality. Would you please fix this and update the app.

**Comment by buzz** [comment]
Could you please provide the output of the console when running the program? This will allow me to check for any exceptions that might have occurred during execution, providing valuable insights into the root cause.

Additionally, if you could share any specific steps or actions that consistently trigger the issue, it would be incredibly helpful. This will enable me to reproduce the error and work towards a resolution.

**Comment by buzz** [comment]
Closed due to inactivity
